/**
 * Pidgeonhole MVP API
 * API for the MVP for Pidgeonhole
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Reference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Reference'));
  } else {
    // Browser globals (root is window)
    if (!root.PidgeonholeMvpApi) {
      root.PidgeonholeMvpApi = {};
    }
    root.PidgeonholeMvpApi.Category = factory(root.PidgeonholeMvpApi.ApiClient, root.PidgeonholeMvpApi.Reference);
  }
}(this, function(ApiClient, Reference) {
  'use strict';




  /**
   * The Category model module.
   * @module model/Category
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Category</code>.
   * @alias module:model/Category
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Category} obj Optional instance to populate.
   * @return {module:model/Category} The populated <code>Category</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('problems')) {
        obj['problems'] = Reference.constructFromObject(data['problems']);
      }
    }
    return obj;
  }

  /**
   * A unique id for a category
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The display name for a category
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * A short description of a category
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/Reference} problems
   */
  exports.prototype['problems'] = undefined;



  return exports;
}));


