/**
 * Pidgeonhole MVP API
 * API for the MVP for Pidgeonhole
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Category', 'model/Error', 'model/Problem', 'model/ProblemInput', 'model/CategoryInput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Category'), require('../model/Error'), require('../model/Problem'), require('../model/ProblemInput'), require('../model/CategoryInput'));
  } else {
    // Browser globals (root is window)
    if (!root.PidgeonholeMvpApi) {
      root.PidgeonholeMvpApi = {};
    }
    root.PidgeonholeMvpApi.CategoriesApi = factory(root.PidgeonholeMvpApi.ApiClient, root.PidgeonholeMvpApi.Category, root.PidgeonholeMvpApi.Error, root.PidgeonholeMvpApi.Problem, root.PidgeonholeMvpApi.ProblemInput, root.PidgeonholeMvpApi.CategoryInput);
  }
}(this, function(ApiClient, Category, Error, Problem, ProblemInput, CategoryInput) {
  'use strict';

  /**
   * Categories service.
   * @module api/CategoriesApi
   * @version 3.0.0
   */

  /**
   * Constructs a new CategoriesApi. 
   * @alias module:api/CategoriesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the categoriesGet operation.
     * @callback module:api/CategoriesApi~categoriesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Category>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List categories
     * Lists all the categories in the system
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand Reference parameters to be expanded
     * @param {module:api/CategoriesApi~categoriesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Category>}
     */
    this.categoriesGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'expand': opts['expand']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Category];

      return this.apiClient.callApi(
        '/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the categoriesIdGet operation.
     * @callback module:api/CategoriesApi~categoriesIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Category} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Problem Category
     * Returns information about a single category of problems.
     * @param {Number} id Unique identifier for a category
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand Reference parameters to be expanded
     * @param {module:api/CategoriesApi~categoriesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Category}
     */
    this.categoriesIdGet = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling categoriesIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'expand': opts['expand']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Category;

      return this.apiClient.callApi(
        '/categories/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the categoriesIdProblemsGet operation.
     * @callback module:api/CategoriesApi~categoriesIdProblemsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Problem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Problems in a category
     * Returns information about the problems in a category
     * @param {Number} id Unique identifier for a category
     * @param {module:api/CategoriesApi~categoriesIdProblemsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Problem>}
     */
    this.categoriesIdProblemsGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling categoriesIdProblemsGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Problem];

      return this.apiClient.callApi(
        '/categories/{id}/problems', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the categoriesIdProblemsPost operation.
     * @callback module:api/CategoriesApi~categoriesIdProblemsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Problem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new problem in a category
     * Create a new problem in a category
     * @param {Number} id Unique identifier for a category
     * @param {module:model/ProblemInput} problem 
     * @param {module:api/CategoriesApi~categoriesIdProblemsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Problem}
     */
    this.categoriesIdProblemsPost = function(id, problem, callback) {
      var postBody = problem;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling categoriesIdProblemsPost");
      }

      // verify the required parameter 'problem' is set
      if (problem == undefined || problem == null) {
        throw new Error("Missing the required parameter 'problem' when calling categoriesIdProblemsPost");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Problem;

      return this.apiClient.callApi(
        '/categories/{id}/problems', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the categoriesIdPut operation.
     * @callback module:api/CategoriesApi~categoriesIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit a category
     * Edit a category
     * @param {Number} id Unique identifier for a category
     * @param {module:model/CategoryInput} category The updated values of this category
     * @param {module:api/CategoriesApi~categoriesIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.categoriesIdPut = function(id, category, callback) {
      var postBody = category;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling categoriesIdPut");
      }

      // verify the required parameter 'category' is set
      if (category == undefined || category == null) {
        throw new Error("Missing the required parameter 'category' when calling categoriesIdPut");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/categories/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
