/**
 * Pidgeonhole MVP API
 * API for the MVP for Pidgeonhole
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TestCase', 'model/TestCaseInput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TestCase'), require('../model/TestCaseInput'));
  } else {
    // Browser globals (root is window)
    if (!root.PidgeonholeMvpApi) {
      root.PidgeonholeMvpApi = {};
    }
    root.PidgeonholeMvpApi.TestCasesApi = factory(root.PidgeonholeMvpApi.ApiClient, root.PidgeonholeMvpApi.TestCase, root.PidgeonholeMvpApi.TestCaseInput);
  }
}(this, function(ApiClient, TestCase, TestCaseInput) {
  'use strict';

  /**
   * TestCases service.
   * @module api/TestCasesApi
   * @version 3.0.0
   */

  /**
   * Constructs a new TestCasesApi. 
   * @alias module:api/TestCasesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the problemsIdTestCasesGet operation.
     * @callback module:api/TestCasesApi~problemsIdTestCasesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TestCase>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Test cases for a problem
     * Returns an array of test cases for a problem
     * @param {Number} id Integer ID for a problem
     * @param {module:api/TestCasesApi~problemsIdTestCasesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TestCase>}
     */
    this.problemsIdTestCasesGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling problemsIdTestCasesGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [TestCase];

      return this.apiClient.callApi(
        '/problems/{id}/test-cases', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the problemsIdTestCasesPost operation.
     * @callback module:api/TestCasesApi~problemsIdTestCasesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TestCase} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new test case for a problem
     * Create a new test case for a problem
     * @param {Number} id Integer ID for a problem
     * @param {module:model/TestCaseInput} testCase The new test case to be created
     * @param {module:api/TestCasesApi~problemsIdTestCasesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TestCase}
     */
    this.problemsIdTestCasesPost = function(id, testCase, callback) {
      var postBody = testCase;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling problemsIdTestCasesPost");
      }

      // verify the required parameter 'testCase' is set
      if (testCase == undefined || testCase == null) {
        throw new Error("Missing the required parameter 'testCase' when calling problemsIdTestCasesPost");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TestCase;

      return this.apiClient.callApi(
        '/problems/{id}/test-cases', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the testCasesIdGet operation.
     * @callback module:api/TestCasesApi~testCasesIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TestCase} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * A test case
     * A single test case
     * @param {Number} id ID for a test case
     * @param {module:api/TestCasesApi~testCasesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TestCase}
     */
    this.testCasesIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling testCasesIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TestCase;

      return this.apiClient.callApi(
        '/test-cases/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
