/**
 * Pidgeonhole MVP API
 * API for the MVP for Pidgeonhole
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PidgeonholeMvpApi);
  }
}(this, function(expect, PidgeonholeMvpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PidgeonholeMvpApi.ProblemsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProblemsApi', function() {
    describe('categoriesIdProblemsGet', function() {
      it('should call categoriesIdProblemsGet successfully', function(done) {
        //uncomment below and update the code to test categoriesIdProblemsGet
        //instance.categoriesIdProblemsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('categoriesIdProblemsPost', function() {
      it('should call categoriesIdProblemsPost successfully', function(done) {
        //uncomment below and update the code to test categoriesIdProblemsPost
        //instance.categoriesIdProblemsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('problemsIdGet', function() {
      it('should call problemsIdGet successfully', function(done) {
        //uncomment below and update the code to test problemsIdGet
        //instance.problemsIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('problemsIdPut', function() {
      it('should call problemsIdPut successfully', function(done) {
        //uncomment below and update the code to test problemsIdPut
        //instance.problemsIdPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('problemsIdTestCasesGet', function() {
      it('should call problemsIdTestCasesGet successfully', function(done) {
        //uncomment below and update the code to test problemsIdTestCasesGet
        //instance.problemsIdTestCasesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('problemsIdTestCasesPost', function() {
      it('should call problemsIdTestCasesPost successfully', function(done) {
        //uncomment below and update the code to test problemsIdTestCasesPost
        //instance.problemsIdTestCasesPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
